configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/data/gwas.smk"
include: "rules/data/gwas_gokcen.smk"
include: "rules/data/splicing_assay.smk"
include: "rules/data/caqtl.smk"
include: "rules/data/dsqtl.smk"
include: "rules/data/gnomad.smk"
include: "rules/data/omim.smk"
include: "rules/data/sat_mut_mpra.smk"
include: "rules/data/siraj.smk"
include: "rules/features/cadd.smk"
include: "rules/features/conservation.smk"
include: "rules/features/dist.smk"
include: "rules/features/enformer.smk"
include: "rules/features/gpn.smk"
include: "rules/features/gpn_msa.smk"
include: "rules/features/grelu.smk"
include: "rules/features/maf.smk"
include: "rules/model.smk"


rule all:
    input:
        #expand(
        #    "results/dataset/{dataset}/{plot}.pdf",
        #    dataset=config["datasets"],
        #    plot=[
        #        "plot",
        #        #"plot_by_chrom",
        #    ]
        #),
        expand(
            #"results/dataset/{dataset}/unsupervised_metrics/{features}.csv",
            #dataset=config["datasets"],
            #"results/dataset/gwas_gokcen_{trait}_matched_9_nonexonic/unsupervised_metrics/{features}.csv",
            #"results/dataset/gwas_gokcen_{trait}_matched_1_nonexonic/unsupervised_metrics/{features}.csv",
            "results/dataset/gwas_gokcen_{trait}_matched_9_nonexonic/metrics_by_chrom_weighted_average/{feature_set}.{classifier}.chrom.csv",
            #trait=["AD", "BMI", "Height"], 
            #trait=eval_traits, 
            trait=traits_high_n, 
            feature_set=[
                "GPN-MSA",
                "CADD",
                "Enformer_L2",
                "Borzoi_L2",
                "Enformer_L2+GPN-MSA+CADD",
            ],
            classifier=[
                #"BestFeature",
                "LogisticRegression",
            ]
            #features=[
            #    "Enformer_L2",
            #    #"Enformer_L2_L2",
            #    "Borzoi_L2",
            #    #"Borzoi_L2_L2",
            #    #"GPN-MSA_absLLR",
            #    "GPN-MSA_InnerProducts",
            #    ###"GPN-MSA_Influence",
            #    ###"GPN-MSA_LLR",
            #    "CADD",
            #    #"GPN_EmbedDists",
            #]
        )

rule all_cadd:
    input:
        expand(
            "results/dataset/{dataset}/unsupervised_metrics/{features}.csv",
            dataset=config["datasets"],
            features=[
                "CADD",
            ]
        )